### ISSUE TITLE
Would XPBD/IBOS be implemented in the future?

### ISSUE THREAD

**Issue by Xayahp** [InteractiveComputerGraphics/PositionBasedDynamics#101]
`PositionBasedDynamics` is really a nice work! and btw I wonder if XPBD & IBOS would be implemented in the future? :-)

**Comment by janbender** [comment]
At least XPBD should be very simple to integrate. However, at the moment we don't have that much time to do this. So it will take a while.

**Comment by Xayahp** [comment]
Thank you~
