### ISSUE TITLE
The difference between Flex and this work

### ISSUE THREAD

**Issue by lyd405121** [InteractiveComputerGraphics/PositionBasedDynamics#105]
I have learned a lot from this  repository and your paper, and I want to implement this repository fully on gpu .
Recent days,  I am learning the Flex engine and Matthias Müller's《Ten Minute Physics》
Here's my video about my work:
![ik](https://user-images.githubusercontent.com/16344694/143983952-8a418238-a8fe-4c17-8eec-7c0c3ff0ec7f.gif)

Here is the difference  I found in rigidbody simulation between this repository and Flex:

In this repository :
model files(ply) → aabb(or kdtree) → collision detect → conact found → sovle constraint

And in Flex:
model files(ply) → particle(discretization, like sdf) → invisible(because Flex is not open source project)

So, the rigidboy simuliton in this repository don't include any particles,  just vertex from the model files. Is that right?
I guess you and Matthias Müller, Miles Macklin are old friends, maybe you know well about the Flex engine   :)

**Comment by korzen** [comment]
This paper explains how Flex works internally [Unified Particle Physics for Real-Time Applications](https://mmacklin.com/uppfrta_preprint.pdf)

**Comment by janbender** [comment]
In this paper they explain that they sample the rigid bodies with particles and then use shape matching to simulate the rigid bodies. In contrast our library uses a proper rigid body model as described (for example) here: 
https://animation.rwth-aachen.de/publication/0513/
