### ISSUE TITLE
render sdf error

### ISSUE THREAD

**Issue by linson7017** [InteractiveComputerGraphics/PositionBasedDynamics#177]
I tried to study how cubic sdf works by rendering sdf while simulating. I found that If rigid was initialized with no translation and scale, i can get a reasonable result. However when i changed the initial position, rotation or scale, i got an unexpected sdf rendering. But the collision detection had no problem. I did not know what happen behind the cubic sdf detection.
Without any initialization
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/a400c29a-af74-4544-b168-e892cead6c49)
With initial position
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/f2a50f78-1a6b-4518-98fe-9ffb130ef96b)
With initial rotation
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/794d4298-e64b-493d-b3c6-7dd1c4baea6e)

This is my rigid initialization code
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/3ecc3b90-ef01-4e8e-b055-23095ef9987f)

My understanding of sdf rendering is to transform the world pos inside aabb to local pos and draw point with negative sdf value calculated by collision object. Why cubic sdf collision object give an unexpected result! Any one knows why. Thanks!
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/2cddf845-9cbd-496b-9416-83f6ec9d4e69)

**Comment by linson7017** [comment]
I found i have made a mistake. I should use the vertex data before initialization when create sdf and use local vertex data when add cubic sdf collision object.
![image](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/assets/22806485/d1385566-61ed-404e-b3f6-14e150def002)

**Comment by janbender** [comment]
The reason for this is that the SDF is computed in the reference configuration of the bunny and during runtime each query vertex is transformed to this reference configutation. So the SDF never changes. Moreover, since we use an SDF of a geometry for all instances of this geometry, this has to be in an independent coordinate system. So all bunnies of a scene just share one SDF.
