### ISSUE TITLE
MSB6003 Error when trying to build on WIndows 11 MS Visual Studio 2019

### ISSUE THREAD

**Issue by gyenyame400** [InteractiveComputerGraphics/PositionBasedDynamics#184]
Hi
I get the following error when trying to build the generated solution from cmake-gui using MS Visual Studio 2019:

error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path '<ROOT_DIR>\PositionBasedDynamics\build\GenericParameters\src\Ext_GenericParameters-build\CMakeFiles\CMakeScratch\TryCompile-c7klt7\cmTC_a814a.dir\Debug\cmTC_a814a.tlog'

**Comment by gyenyame400** [comment]
Another error down the log output:

Error	C1083	Cannot open include file: 'ParameterObject.h': No such file or directory (compiling source file <ROOT_DIR>\PositionBasedDynamics\Utils\SceneLoader.cpp)	Utils	<ROOT_DIR>\PositionBasedDynamics\Utils\SceneLoader.h

**Comment by janbender** [comment]
Did you install git?

Am 30. April 2024 14:03:33 MESZ schrieb gyenyame400 ***@***.***>:

**Comment by gyenyame400** [comment]
Solved.
I needed to configure the environment variable VCTargetsPath.
In my case MS VS2019 it was: 

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160**\**

(With the trailing slash)
After that all went smoothly.

Thanks
