### ISSUE TITLE
compiling error under ubuntu 

### ISSUE THREAD

**Issue by bnamazi** [InteractiveComputerGraphics/PositionBasedDynamics#20]
Hi,

I ve been trying to compile the new library on ubuntu 16.04. After fixing a couple of errors (adding the required header files for openmp, etc) it gives me this error while linking the executable:

../../lib/libSimulation.a(TimeStepController.cpp.o): In function `PBD::TimeStepController::step(PBD::SimulationModel&)':
TimeStepController.cpp:(.text+0x3a2): undefined reference to `PBD::TimeIntegration::semiImplicitEuler(double, double, Eigen::Matrix<double, 3, 1, 0, 3, 1>&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
TimeStepController.cpp:(.text+0x5a3): undefined reference to `PBD::TimeIntegration::semiImplicitEulerRotation(double, double, Eigen::Matrix<double, 3, 3, 0, 3, 3> const&, Eigen::Quaternion<double, 0>&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
TimeStepController.cpp:(.text+0x817): undefined reference to `PBD::TimeIntegration::semiImplicitEuler(double, double, Eigen::Matrix<double, 3, 1, 0, 3, 1>&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
.....

I checked it with different gcc versions (4.9, 5 and 6).

I d appreciate any help.

Regards,
Babak

**Comment by janbender** [comment]
Hi, 

that is strange since the method is implemented in TimeIntegration.cpp. Did you generate make files with cmake?

Jan

**Comment by bnamazi** [comment]
Hi Jan,

thanks for your reply.
Yes. I used  cmake to generate the make file. the previous version is compiled using cmake without error. here is what i did: (in the parent folder)
cmake .
make
not sure where i should change in the generated makefile.

**Comment by janbender** [comment]
Hi,

sorry, I cannot reproduce your problem. I tested it on an OpenSuse 
system and it worked fine for me.

Jan


Am 22.06.2016 um 00:31 schrieb bnamazi:

**Comment by krips89** [comment]
Hello, I got the same problem in my Ubuntu 14.04. The problem is libSimulation does not link to the actual code even though it is implemented. 
Following line at the end of CMakeLists.txt of Simulation fixed the issue:

`target_link_libraries(Simulation PositionBasedDynamics)`

**Comment by janbender** [comment]
I added the line to the CMakeLists.txt. Hope that helps.
