### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by apapaxiong** [InteractiveComputerGraphics/PositionBasedDynamics#21]
I test the DeformableCollisionDemo,

void OBJLoader::loadObj
{
    ....
	else if(type_str == "vt")
		{
	                .....
			texcoords.push_back(tex);  // this will cause the following error ! see below !
			vt = true;
        }
}
template<> EIGEN_STRONG_INLINE void pstore<double>(double* to, const Packet2d& from) { EIGEN_DEBUG_ALIGNED_STORE _mm_store_pd(to, from); }

Exception thrown at 0x013ED11C in DeformableCollisionDemo_d.exe: 0xC0000005: Access violation reading location 0x00000000.

How to fix that? Almost every demo seems to have access violation problem.

**Comment by janbender** [comment]
Hi,

can you give me more details? Which OS do you use? Did you use an x86 or 
x64 configuration? It seems that there are some problems when compiling 
the library with a x86 configuration on a 64bit system.

Jan


Am 30.06.2016 um 13:02 schrieb apapaxiong:

**Comment by apapaxiong** [comment]
OS: Windows 7
IDE: visual studio 2015
I used a x86 configuration

**Comment by apapaxiong** [comment]
It works when I change everything to x64 :)
