### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by jmkinzer** [InteractiveComputerGraphics/PositionBasedDynamics#22]
Apologies if I missed this somewhere but it should be noted in the readme that this library only supports 64 bit builds (at least on MSVC you'll get crashes due to alignment issues on 32 bit builds). Thus on windows you'll need to:
- Ensure you're building against 64 bit boost
- Run something like
   `cmake -G "Visual Studio 14 2015 Win64" `
   (At least on my system cmake really wants to configure for a 32 bit build by default)

**Comment by janbender** [comment]
I added a comment in the readme file.
