### ISSUE TITLE
CMake configuration error.

### ISSUE THREAD

**Issue by svedach** [InteractiveComputerGraphics/PositionBasedDynamics#26]
I tried to build the project to Visual Studio 2015 64bit with Boost 1.62.0, during configuration error occurs

"CMake Error at C: / Program Files / CMake / share / cmake-3.6 / Modules / FindBoost.cmake: 1753 (message):
   Unable to find the requested Boost libraries.

   Boost version: 1.62.0

   Boost include path: D: / SAV / PROJECTS / NeuRob / Info and Libs / boost_1_62_0

   Could not find the following static Boost libraries:

           boost_filesystem
           boost_system

   No Boost libraries were found. You may need to set BOOST_LIBRARYDIR to the
   directory containing Boost libraries or BOOST_ROOT to the location of
   Boost.
Call Stack (most recent call first):
   Demos / SceneLoaderDemo / CMakeLists.txt: 7 (find_package) "

How to fix it? Thank you.

**Comment by Davelis** [comment]
Hey, 
As far as i am concerned (trying to test PBD myself this days) only SceneLoaderDemo requires boost filesystem & system libs. 
I had a similar issue so i will try to help without taking any responsibility over this. 
What i did : 

    1. Open cmd (or Powershell) and navigate to Boost path .
**Enter the following commands:**

    2. ./bootstrap.bat
    3. ./b2.exe link=static runtime-link=static --with-filesystem --with-system

**This two commands will built for you the static libraries that are required for SceneLoaderDemo under the folder Boost/stage/lib .**   
   
      1.    Go to PositionBasedDynamics/extern folder and create a Boost directory , under it create an include one and a lib one . 
      2.    Under include directory place Boost/boost/ folders* (header/hpp files) .
      3.    Under lib directory place the lib files generated at Boost/stage/lib from step 2 & 3.

 
**Now move on to changing the CMakeLists.txt under Demos/SceneLoaderDemo :**

     1. Open the text and replace the top with this :: 
                                                                                                                             
     set(Boost_USE_STATIC_LIBS ON)
     #add_definitions(-DBOOST_ALL_NO_LIB)
     set (BOOST_ROOT ${CMAKE_SOURCE_DIR}/extern/Boost)
     set (Boost_LIBRARY_DIRS ${CMAKE_SOURCE_DIR}/extern/Boost/stage/lib)
     find_package( Boost COMPONENTS filesystem system REQUIRED )
     include_directories( ${Boost_INCLUDE_DIR} )



Hope i helped.

**Comment by janbender** [comment]
As Davelis already told you, first need to build boost. But then you can simply add the parameter BOOST_ROOT in the cmake gui and set it to the folder where you installed boost. Then cmake will find everything.
