### ISSUE TITLE
Visual Studio 13 : error C3646: 'noexcept': Unknown override specifier. 

### ISSUE THREAD

**Issue by Davelis** [InteractiveComputerGraphics/PositionBasedDynamics#27]
Good evening, 

I am trying to build the Demos so i can test your library but i am facing an issue.

I generate **Visual Studio 13 .sln** files with the use of **CMake** and i am getting the C3646 error i placed on title. As i far as i am concerned **Visual Studio 13** does not support noexcept and that's why i am having this issue.

So i want to know if there's any work-around you have already been over with (because obviously it won't let me compile). 
Also since you claim that PBD works on Windows 7 i am guessing you used **Visual Studio 15** for implementing/testing ?

Thanks a lot.

**Comment by janbender** [comment]
I developed the library first using Visual Studio 2013 but since a few months I switched to VS 2015. I have never seen an error like this. Do you have more information about it? Where does the error occur?

**Comment by Davelis** [comment]
Hey, 
I am posting a screenshot . PBD was built using : "cmake .. -G "Visual Studio 12 Win64" 
http://prntscr.com/cqgyih

Also , i did move to Visual Studio 2015 PBD compiles fine but i found 2 other errors .

First one is AntTweakBar always throws an OpenGL 501 error which can be seen here : http://prnt.sc/cqhbc9

Second one is whenever i close a Demo from debug session it throws this : 
 http://prntscr.com/cqhbla

Do you happen to know anything about those?
Thanks in advance.

**Comment by janbender** [comment]
Sorry but I cannot reproduce these problems. Did you use a x64 target?

**Comment by Davelis** [comment]
Hi, 
I rebuild the library and it was fine.

May I ask though, do you have any demos or any work done on "cutting" meshes by selecting triangles with the mouse. Or anything similar?

Thanks.

**Comment by janbender** [comment]
No, at the moment we have no cutting demos.
