### ISSUE TITLE
examples without boost

### ISSUE THREAD

**Issue by attilaz** [InteractiveComputerGraphics/PositionBasedDynamics#30]
This engine seems interesting, but it would be great to be able to try the examples without the huge boost dependency. 
This whole dependency stuff just wastes your possible users' time.
As far as I can see it only uses to parse json files, that is doable in hundreds of lines of c code, instead of using a 500MB HUGE library.

**Comment by janbender** [comment]
Just integrate you json parser code and send me a pull request. I just used boost since we have no time to implement this on our own.
