### ISSUE TITLE
'noexcept' error when build for X86 debug

### ISSUE THREAD

**Issue by luozhipi** [InteractiveComputerGraphics/PositionBasedDynamics#31]
[solved]
add this section into 'common.h'

#ifndef _MSC_VER
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif

and then

void operator delete(void* block, int const block_use, char const*  file_name, int const line_number) **NOEXCEPT** { \
		\
			return _aligned_free_dbg(block); \
		} \
		void operator delete[](void* block, int const block_use, char const*  file_name, int const line_number) **NOEXCEPT** { \
			return operator delete(block, block_use, file_name, line_number); \
		}

**Comment by janbender** [comment]
I just built PBD with x86 debug and I had no errors at all. Which Compiler did you use?

**Comment by luozhipi** [comment]
vs 2013 x64

**Comment by janbender** [comment]
Should be solved now.
