### ISSUE TITLE
Reg. Windows Compilation

### ISSUE THREAD

**Issue by Balar86** [InteractiveComputerGraphics/PositionBasedDynamics#33]
Hi,

I have downloaded the source and trying to compile for Windows 10 with VS2012.

Creates a .sln file using CMake application, when I build my application it throws many errors related to "Eigen::aligned_allocator" like this,

Error	238	error C2955: 'Eigen::aligned_allocator' : use of class template requires template argument list (..\..\PositionBasedDynamics\TimeIntegration.cpp)	D:\PRAPTISENSE\New_Physics\PositionBasedDynamics-master\Common\Common.h	36	1	PositionBasedDynamics

Please let me know what would be the issue, Am I missing something here or do I have to download Eigen code base?

I have seen the video, the work is awesome! I believe all the simulation done on GPU level!!

Looking forward to your answer..

Thanks and Regards,
Bala

**Comment by zhaoxiaohan** [comment]
Thank you for your interest in this project.

I am sorry to say i am not the writer, which means i copied it from the creator. For detailed informatin, you may contact the creator. His email is bender@cs.rwth-aachen.de.

i am now a master student of Beihang University. Welcome to communicate with me.

At 2016-11-07 23:12:24, "Bala" <notifications@github.com> wrote:


Hi,

I have downloaded the source.

Creates a .sln file using CMake application, when I build my application it throws many errors related to "Eigen::aligned_allocator" like this,

Error 238 error C2955: 'Eigen::aligned_allocator' : use of class template requires template argument list (....\PositionBasedDynamics\TimeIntegration.cpp) D:\PRAPTISENSE\New_Physics\PositionBasedDynamics-master\Common\Common.h 36 1 PositionBasedDynamics

Please let me know what would be the issue, Am I missing something here or do I have to download Eigen code base?

I have seen the video, the work is awesome! I believe all the simulation done on GPU level!!

Looking forward to your answer..

Thanks and Regards,
Bala

**Comment by janbender** [comment]
Did you choose a 32bit build target on a 64bit system?
