### ISSUE TITLE
solve_EdgeEdgeDistanceConstraint error on end points

### ISSUE THREAD

**Issue by nervoussystem** [InteractiveComputerGraphics/PositionBasedDynamics#38]
Edge edge distance constraint computes wrong distance when the intersection is past the end points of both segments. If the intersection is past the end of one segment, it needs to recompute the closest point on the other

Instead of

```
if (s < 0.0) s = 0.0;
if (s > 1.0) s = 1.0;
if (t < 0.0) t = 0.0;
if (t > 1.0) t = 1.0;
```
should be something like

```
if (s < 0.0) {
  s = 0.0;
  t = f / d;
}
else if (s > 1.0) {
  s = 1.0;
  t = (f+b) / d;
}
if (t < 0.0) {
  t = 0.0;
  if (e<0) {
    s = 0.0;
  }
  else if (e>a) {
    s = 1.0;
  }
  else {
    s = e / a;
   }
}
```

**Comment by janbender** [comment]
Sorry, currently I don't have the time to look for this constraint. If you have tested your solution it would be nice if you could send me a pull request.
