### ISSUE TITLE
Why does the mesh in BarDemo keep vibrating？

### ISSUE THREAD

**Issue by RainVector** [InteractiveComputerGraphics/PositionBasedDynamics#46]
I add a static rigidboy as a ground in the BarDemo. The bar are placed on the ground and simulated with FEM based PBD method. But the vertices of the mesh keep vibrating with small  amplitude.  
When I use Volume Constraints, this bar doesn't vibrate anymore. 
So I am not clear about whether  the vibrating problem is related to the FEM based PBD method or the Gauss-Seidel solver.

**Comment by janbender** [comment]
Probably this problem occurs due to the penalty forces in the collision handling. Maybe you could reduce the stiffness.



Am 21. Januar 2018 09:01:13 MEZ schrieb RainVector <notifications@github.com>:
>I add a static rigidboy as a ground in the BarDemo. The bar are placed
>on the ground and simulated with FEM based PBD method. But the vertices
>of the mesh keep vibrating with small  amplitude.  
>When I use Volume Constraints, this bar doesn't vibrate anymore. 
>So I am not clear about whether  the vibrating problem is related to
>the FEM based PBD method or the Gauss-Seidel solver.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/issues/46

-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by janbender** [comment]
Maybe this comes due to the inversion handling. Can you send me the code?

**Comment by RainVector** [comment]
I haven't change the source code. In the bar demo, if you set both ends of the bar static and view with vireframe mode , you can see the mesh vertices are keeping vibrating gently, especially at the the **Middle** part.
