### ISSUE TITLE
How to run the project after make

### ISSUE THREAD

**Issue by jackscrew** [InteractiveComputerGraphics/PositionBasedDynamics#47]
This is not an issue. I am new to CMake. I finally have the targets built after cmake. and make . How do I run the program now? Have googled, but not been of much help.
Thanks

**Comment by termi3** [comment]
If you run CMake you select compiler (Visual Studio or some other)
With the latest version of CMAKe there is third button –open the editor, OR just start this tool, and look for the folder where the project is created and COMPILE IT.
There will be several projects with your project three – select one of the demos,
And try to “debug” it  - it starts the debug version.
Alternative – you compile in “release” modus  (check your tool for the seeting)
Go to the “release folder” (can be in bin/ or so) and find the exe


Von: jackscrew [mailto:notifications@github.com]
Gesendet: Sonntag, 21. Januar 2018 18:22
An: InteractiveComputerGraphics/PositionBasedDynamics <PositionBasedDynamics@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: *** GMX Spamverdacht *** [InteractiveComputerGraphics/PositionBasedDynamics] How to run the project after make (#47)


This is not an issue. I am new to CMake. I finally have the targets built after cmake. and make . How do I run the program now? Have googled, but not been of much help.
Thanks

**Comment by jackscrew** [comment]
Okay, thank you for your help, termi3.

**Comment by jackscrew** [comment]
I was now able to find the executables in /bin . Got it, thanks.
