### ISSUE TITLE
Collision handling

### ISSUE THREAD

**Issue by airatsa** [InteractiveComputerGraphics/PositionBasedDynamics#49]
According to PBD paper (http://matthias-mueller-fischer.ch/publications/posBasedDyn.pdf) collision constraints are handled in the same way (and solved in the same loop) as spring constraints.
So collision contraints affect postions.

In the PositionBasedDynamics library collision constraints are solved in a separate loop and affect velocities rather than position.

Why is it implemented in such a way?

**Comment by janbender** [comment]
Müller et al. only handle collisions between deformable solids and neglect repulsion forces which is acceptable for deformables. However, in our library we currently handle only collisions between rigid bodies where a repulsion is important for a realistic impression. However, repulsion can only be handled realistically on velocity level and not on position level. 

Moreover, I think our solution works well in practice as you can see here: 

https://www.youtube.com/watch?v=x_Iq2yM4FcA

**Comment by airatsa** [comment]
I agree on handling repulsion on velocity level, I faced it in my own experiments with PBD.
Can't position-level constraint handling (along with velocity level) be useful? For example, rubber ball jumping on the rigid floor.
