### ISSUE TITLE
x

### ISSUE THREAD

**Issue by RainVector** [InteractiveComputerGraphics/PositionBasedDynamics#51]

**Comment by ftd-sjy** [comment]
Hello, @RainVector ,I have the similar problem with you, but I see you closed this problem, I want to know where did you find the derivations of this constraints?Thanks!

**Comment by RainVector** [comment]
Hi @ftd-sjy, I just find this [repo](https://github.com/DanielChappuis/reactphysics3d) use the same solution when solving Joint constraints. And @DanielChappuis give us  the derivations in his [document](http://danielchappuis.ch/download/ConstraintsDerivationRigidBody3D.pdf). It just contains the deriavetions of velocity constraints. For position constraints, you can refer to this [issue](https://github.com/DanielChappuis/reactphysics3d/issues/47)
