### ISSUE TITLE
How can I get the FPS of this program? Also about the value set of iterations.

### ISSUE THREAD

**Issue by ftd-sjy** [InteractiveComputerGraphics/PositionBasedDynamics#52]
Dear authors:
Thanks for your repository first!
But I have some problems when I use the SceneLoaderDemo. **Now I want to calculate the FPS of this program.** By reading your code, I found that the render function is this function:
**void  render(); (in SceneLoaderDemo.cpp)**
Plus, the main PBD solve function is this function:
**void timestep(): (also in SceneLoaderDemo.cpp)**
In this timestep() function, I found that solve is carried by call  **sim.step(model);**
**But i don't know why you call the sim.step(model) continuously for 8 times for each call of the timestep() function.** The original code as follows:  (the other unnecessary codes are  omitted)
```
void timestep()
{ ... 
	//simulation code 
	for (unsigned int i = 0; i < 8; i++)
		sim.step(model); 
...}
```
**I changed this code to(by added the variable turns):**
```
void timestep()
{ ... 
        int turns=8;
	//simulation code 
	for (unsigned int i = 0; i < turns; i++)
		sim.step(model); 
...}
```
 What is more, I also used the C++ chrono for timing. **I added these timing code at the beginning of the render() function to calculate FPS** (also in the SceneLoaderDemo.cpp)  : 
```
void render()
{
_...//unnecessary codes are omitted_
	//calculate FPS
	if (!doPause)
	{
		if (frames_sumt.first == 0)
		{
			frames_sumt.first++;
			fps_tp1 = high_resolution_clock::now();
			fps_tp2 = fps_tp1;
		}
		else
		{
			fps_tp2 = high_resolution_clock::now();
			milliseconds_duration t_a_frame = duration_cast<milliseconds_duration>(fps_tp2 - fps_tp1);
			fps_tp1 = fps_tp2;
			frames_sumt.first++; //frames++
			frames_sumt.second += t_a_frame.count(); //the unit of sumt is ms
		}
	}
...
} // (frames_sumt is a c++ pair<int, double>)
```
When I set this variable **turns** in timestep() equals 8, the fps is about 39.6fps , and the running animation seems very smoothly.
But when I set this variable **turns** to a smaller value , for example ,1, the fps is becoming more higher about 59.8fps, while the running animation seems more slowly in contrast.
(timeStepSize=0.005, maxIter=5, maxIterVel=5)
**I don't know why such situation occurs.
Plus, does my way to calculate FPS right?**
Thank you again, look forward to your reply.

**Comment by janbender** [comment]
First, we never cared about FPS since this is not relevant in simulation. If you want to have a real-time simulation you must ensure that your method needs less time than the size of our time step. 

Maybe we should remove MIN_PARALLEL_SIZE since this is an old artefact. Thanks for the hint. 

> Does the initial 5ms set of the size of time step has any use?

Yes! This is the time step size of your time integrator. If you want to know more about the simulation method and the time integration, take a look at our tutorial:

https://www.animation.rwth-aachen.de/publication/0553/

> Plus, i see that the collision constraints are solved not using the openMP, can i perform a similar algorithm to parallel the contact solve?

Yes. You can implement a graph coloring that works on the fly or use a Jacobi solver which can be parallelized easily but also converges slower. 

> Last but not least, if i want to set some particles static in the particle model, can i simply set the mass of selected particles to zero, does it will introduce any additional error?

Yes, this exactly was the idea.
