### ISSUE TITLE
How to compute self-collision constraint gradient?

### ISSUE THREAD

**Issue by daiday** [InteractiveComputerGraphics/PositionBasedDynamics#53]
I've some trouble with the constraint gradient. The self collision constraints  complicate me a lot, there are two cross product in the formula:

**C(q,p1,p2,p3) = (q-p1) * (p2-p1)x(p3-p1) / |(p2-p1)x(p3-p1)| - h**

I read it from the PBD paper, point triangle collision constraint.
BUT I don't know how to compute the gradient C. It's too hard for me.
I also notice at the end of PBD paper, Appendix A, give the Gradient of normalized cross product. But it still baffle me.
(I found $$ math format is not supported, sorry for I don't write the latex math formula)

**Comment by janbender** [comment]
This is just straight-forward, e.g. the derivative with respect to q is:

(p2-p1)x(p3-p1) / |(p2-p1)x(p3-p1)|

since the derivative of q with respect to q is the identity matrix. Alternatively you can use a constraint based on barycentric coordinates like in our implementation: 

https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/blob/master/PositionBasedDynamics/PositionBasedDynamics.cpp#L306

**Comment by daiday** [comment]
Thanks for replying. 
Yes, the partial C/partial q is easy to compute. But how to calculate the partial C / partial p1?
Actually, I have seen a solution before([here](https://media.contentapi.ea.com/content/dam/eacom/frostbite/files/gdc2018-chrislewin-clothselfcollisionwithpredictivecontacts.pdf)). 
![4edzzk fy2 o6 a dp2](https://user-images.githubusercontent.com/2535570/41144753-7d49a072-6b30-11e8-80e7-96d75549317e.png)

But I can not get the right result. When I compute the N, I ignore the |n|. I think it's 1.  I do not know where goes wrong( the collision detect results or the gradient constraint formula). 

So, is the formula right? Or it's a simplified formula?

I would take a good look at the function **solve_TrianglePointDistanceConstraint**.

**Comment by janbender** [comment]
I don't think that this is correct. If I derive (2) with respect to p1, why should p get lost in the result. So (3) must be wrong. Btw. you can easily test this with our generic constraints, where the gradient is determined numerically.

**Comment by daiday** [comment]
I've tried to use solve_TrianglePointDistanceConstraint, I found it simply handle the point triangle constraint as point point distance constraint. The idea is very clear and effect. When the speed of the cloth is too fast, it would penetrate. I should do more work about preventing penetration.
Thanks again!

**Comment by nixon-voxell** [comment]
hi @daiday may I know if you came to a good solution for cloth self collision for point tri and edge edge?

**Comment by daiday** [comment]
> hi @daiday may I know if you came to a good solution for cloth self collision for point tri and edge edge?

if you care about efficiency, then no. or try to read [gdc2018](https://www.ea.com/frostbite/news/cloth-self-collision-with-predictive-contacts).

**Comment by nixon-voxell** [comment]
> if you care about efficiency, then no. or try to read [gdc2018](https://www.ea.com/frostbite/news/cloth-self-collision-with-predictive-contacts).

thanks @daiday , so you just went for point-point?
