### ISSUE TITLE
How to handle collision between elastic rods and rigidbody?

### ISSUE THREAD

**Issue by ipoirot** [InteractiveComputerGraphics/PositionBasedDynamics#54]
Dear authors:
How to handle collision between elastic rods and rigidbody?

**Comment by janbender** [comment]
This is not implemented yet. However, you could simply use the signed distance function of a capsule for each rod segment for the collision detection. This function is described here:

http://iquilezles.org/www/articles/distfunctions/distfunctions.htm

**Comment by ipoirot** [comment]
Dear authors:
Thanks a lot for your kind and detailed reply, it's very helpful.
