### ISSUE TITLE
Issues generating project

### ISSUE THREAD

**Issue by Eths33** [InteractiveComputerGraphics/PositionBasedDynamics#55]
When trying to generate the project using "PositionBasedDynamics-master" as the source and a new folder as the target build location I get the following message. 

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1811 (message):
  error: could not find git for clone of ExternalProject_Discregrid
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2565 (_ep_add_download_command)
  CMakeLists.txt:28 (ExternalProject_Add)

Do I need to include a path to your project Discregrid?

**Comment by janbender** [comment]
Seems that Cmake does not find your git installation. Did you install git?

**Comment by Eths33** [comment]
Thank you for the fast reply. Everything works now.
