### ISSUE TITLE
Cloth keep vibrating when handling collision

### ISSUE THREAD

**Issue by daiday** [InteractiveComputerGraphics/PositionBasedDynamics#56]
Hello everyone:
I'm trying to sim a tight cloth ( two sewing quad cloth surrounding two spheres, see the pic below) 
But the cloth keeps vibrating.

![1](https://user-images.githubusercontent.com/2535570/42202836-7603dafa-7ecf-11e8-9d14-9831962aa3c3.gif)

My collision constraint projection is very simple:
```
bool projection( Garment& garment )
{
    vec3& p   = garment.P()[ _p ];
    vec3  dir = p - _q;

    float C = dot( dir, _n );
    if ( C >= 0.0)
        return true;

    vec3 dp = _n * ( -C );
    p += dp * 1;

    return false;
}
```
_q, _n is the collision plane parameters. 
The cloth keeps vibrating when I use larger stretch stiffness( or use smaller compliance with XPBD method ).  
What should I do to avoid cloth vibrating except changing cloth stiffness?

**Comment by janbender** [comment]
If you simulate very stiff cloth models in such a scenario, this requires many iterations to converge. I am not sure if our current contact constraint is suitable for situations with large stiffnesses since it is partially based on penalty forces.

**Comment by daiday** [comment]
Thanks for replying. I've found that solving constraints with different orders leads to different results. I tried to solve collision constraints before inner constraints, it's better than mixing all the constraints together.
Thanks again!
