### ISSUE TITLE
Cloth Continuous Collision Detection

### ISSUE THREAD

**Issue by huminzheng** [InteractiveComputerGraphics/PositionBasedDynamics#57]
Dear authors:
How to handle continuous collision between cloth models，cloth model self-collision ，collision between cloth model and deformable rigid body ( that you can deform the mesh of the rigid body at each simulation step)？ Could you give me some  suggestions?

**Comment by huminzheng** [comment]
Thank you

**Comment by cesss** [comment]
> "Robust Treatment of Collisions, Contact and Friction for Cloth"

What would be the proper place in the code for adding the procedures explained in that paper?
