### ISSUE TITLE
Cannot find the demo of "Direct Position-Based Solver for Stiff Rods"

### ISSUE THREAD

**Issue by wavedig** [InteractiveComputerGraphics/PositionBasedDynamics#59]
I notice this "Crispin Deul added the implementation of his paper Deul, Kugelstadt, Weiler, Bender, "Direct Position-Based Solver for Stiff Rods", Computer Graphics Forum 2018 and a corresponding demo". But There is no corresponding demo that I can find in the project. The actual demo is where?

**Comment by janbender** [comment]
It is in the folder "StiffRodsDemos".
