### ISSUE TITLE
PBD lib is compiling with errors in case of too old compiler

### ISSUE THREAD

**Issue by NadineAB** [InteractiveComputerGraphics/PositionBasedDynamics#68]
Hello,

I do use the PBD lib as submodule in my code, however, I have observed lately that the PBD lib is compiling with errors in case of too old compiler. As in the DiscreGrid lib, the required compiler is gcc 6.3 and more and clang 6.0 is not supported. I would like to suggest if you could kindly add a command in the cmake of the PBD can check that the compiler is not too old, and trigger error otherwise.

**Comment by janbender** [comment]
There should be a command that says that at least C++11 support is requried.

**Comment by NadineAB** [comment]
I am afraid that the problem occurs when clone and build the DiscreGrid lib within the PBD lib
