### ISSUE TITLE
Xcode - compile error

### ISSUE THREAD

**Issue by alelordelo** [InteractiveComputerGraphics/PositionBasedDynamics#69]
Hello Jan and PDB team,

Could you help with that?

I had the following build error when I try to compile on Xcode.

The C compiler identification is AppleClang 10.0.0.10001145
The CXX compiler identification is AppleClang 10.0.0.10001145
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at Demos/ClothDemo/CMakeLists.txt:47 (set_target_properties):
set_target_properties called with incorrect number of arguments.

CMake Error at Demos/ClothDemo/CMakeLists.txt:48 (set_target_properties):
set_target_properties called with incorrect number of arguments.

CMake Error at Demos/ClothDemo/CMakeLists.txt:49 (set_target_properties):
set_target_properties called with incorrect number of arguments.

Configuring incomplete, errors occurred!
See also "/Users/xxxxx/Desktop/CMakeFiles/CMakeOutput.log".

**Comment by janbender** [comment]
Sorry but we have no MacOS to test this. Maybe another Mac user can help you.
If you can solve it, please send us a pull request.

**Comment by alelordelo** [comment]
Ok, thanks Jan. Will update if I male any progress

**Comment by NadineAB** [comment]
Hello,
It works fine on my mac pro, however, I am using qtcreator with gcc as compiler. Please also bear in mind that you need openmp to be already installed on your mac.

best wishes
