### ISSUE TITLE
Demo's performance

### ISSUE THREAD

**Issue by darkowic** [InteractiveComputerGraphics/PositionBasedDynamics#71]
Hello! First, thanks for publishing this library. Really helpful with learning PDB.

I am checking out this library and running demos. But performance in demos is so poor (cloth simulation demo):
```
Average time SimStep: 208.505 ms
Average time simulation step: 208.503 ms
Average time position constraints projection: 180.218 ms
Average time collision detection: 11.3226 ms
```
What am I doing wrong?

Disclaimer: I am a newbie in these topics.

**Comment by janbender** [comment]
This should be definitely below 10ms per step. Are you sure that you built the release and not the debug version?

**Comment by darkowic** [comment]
You are obviously right...
```
OpenGL version 4.6
Using GLEW 1.12.0
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1070/PCIe/SSE2
Version: 4.6.0 NVIDIA 390.77
Number of triangles: 4802
Number of vertices: 2500
Number of triangles: 12
Number of vertices: 8
Number of triangles: 1600
Number of vertices: 800
Average time SimStep: 14.0998 ms
Average time simulation step: 14.099 ms
Average time position constraints projection: 1.05808 ms
Average time collision detection: 0.564046 ms
```
Thank you for pointing me the error :)

Btw it is still slow IMHO. Is it because of the demo? There are not too many vertices and my PC (i5 5700k) is definitely powerful enough to do it faster.

**Comment by janbender** [comment]
This is still a bit strange since the position constraints projection and collision detection are the steps with the main computational effort. In your simulation this takes less than 2ms while the total simulation step requires 14ms. However, there are no other costly steps to perform.
