### ISSUE TITLE
Wind interaction in the trees video?

### ISSUE THREAD

**Issue by cesss** [InteractiveComputerGraphics/PositionBasedDynamics#72]
Looking at the trees video, is it a wind simulation, or fake forces? Are the trees demos available, for having a look at how the wind or wind-like forces have been modelled? And, by the way, what tree generator did you use? The pine geometry looks really nice!

**Comment by janbender** [comment]
The simulation of the trees was performed using our open-source framework: 
https://github.com/InteractiveComputerGraphics/PositionBasedDynamics

The wind was no real simulation. The trees were generated using a Blender tool.

**Comment by cesss** [comment]
Is the PositionBasedDynamics framework ready for considering the interaction of particles into the simulated bodies? I mean: Is the framework ready for taking particle hits as forces applied into the rigid bodies? If affirmative, it should be trivial to take particles from a wind simulator and push them into a simulation done in PositionBasedDynamics.

**Comment by janbender** [comment]
Yes, that is possible. You can take a look at SPlisHSPlasH how the particles interact with the rigid bodies.

**Comment by cesss** [comment]
Thanks!! I built SPlisHSPlasH, and I'm seeing at those demos right now. But it seems that the PositionBasedDynamics demos are not built (I mean that SPlisHSPlasH has demos with rigid bodies, but however PositionBasedDynamics is built as a library only, and the executables and demos are not built, or at least I cannot find them).

Is it possible to build the PositionBasedDynamics executables from the same SPlisHSPlasH source tree? It would be much more convenient to me, because I prefer to avoid duplicating sources.

**Comment by cesss** [comment]
I just found a CMake variable that, if changed, allows to build the PositionBasedDynamics executables from the SPlisHSPlasH source. I'm closing this, thanks a lot for your help!!!

**Comment by cesss** [comment]
BTW, one more question about this topic: If you had to simulate the deformation of trees due to wind, with SPlisHSPlasH (I'm supposing it can simulate wind as a fluid, although I believe there are no demos about that), how would you model the trees? With tetrahedral meshing of the trunk and branches? And what about the leaves? Would you make the leaves as surfaces without thickness, or do you think it will work better with tetrahedral elements too (and thus some small thickness) ?

**Comment by janbender** [comment]
We modeled the trees as elastic rods including the leaves. See here:

https://animation.rwth-aachen.de/publication/0557/

**Comment by cesss** [comment]
Thanks! I found that the paper explains the tree scene pretty well. I still have to understand why the software lets you see the tetrahedral mesh, because I think I'm understanding that PBD is mesh-less, but I think I'll understand it with after a deeper study of the paper.

**Comment by janbender** [comment]
PBD is just a method to solve constraints. I can be meshless but most methods are based on meshes.
