### ISSUE TITLE
"DirectPositionBasedSolverForStiffRodsDemo" add collision.

### ISSUE THREAD

**Issue by CharlesQHappy** [InteractiveComputerGraphics/PositionBasedDynamics#77]
1.what the steps are to add collision between the rod and any complex model(which is not primitive geometry)?i can't find the acess.
2.is the source code of the paper《Direct Position-Based Solver for Stiff Rods》opened?The vedio is great and might solve my problem directly.

**Comment by charlesyulife** [comment]
i  found the function" readTriangleModels",it seems to realated complex models. but how to config the data of the item "TriangleModels" in "wilberforce_scene.json" file?

**Comment by Allen3Young** [comment]
> 1.what the steps are to add collision between the rod and any complex model(which is not primitive geometry)?i can't find the acess.
> 2.is the source code of the paper《Direct Position-Based Solver for Stiff Rods》opened?The vedio is great and might solve my problem directly.

I am also interested in the implementation of "Direct Position-Based Solver for Stiff Rods". I think there is only a demo for Wilberforce Pendulum for now. Unluckily, there is no source code for the Formation of Plectonemes.

I did some changes in the function void readScene() and got collision detection to work. Basically I add a collision model to each segment of a rod. Note that you'd better not detect collision of two adjacent segments. And also in my case, there is possibly a bug in StiffRodsSceneLoader.cpp, but I have not figured out how it prevents collision checking working. The solution is in PBD::StiffRodsSceneLoader::readStiffRodsScene(), do not use the member variable m_json, define a local variable to replace it. And in void StiffRodsSceneLoader::parseStiffRodsData(), use the parameter "child" to replace "m_json" in the function.  I don't know why but the member variable m_json makes collision detection fail.

Hope it helps.
