### ISSUE TITLE
Clothdemo compilation failed

### ISSUE THREAD

**Issue by wil1996** [InteractiveComputerGraphics/PositionBasedDynamics#78]
Dear author：
     In the compilation process of clothdemo, "CMake Error at CMakeLists.txt:52 (VIS_SOURCE_GROUPS): Unknown CMake command "VIS_SOURCE_GROUPS"." always appears. How do you solve it?

**Comment by wil1996** [comment]
I compile it under windows. Cmake and vs versions follow your requirements.

**Comment by janbender** [comment]
This is strange, the command is defined in Demos/Visualization/CMakeLists.txt which is included in Demos/CMakeLists.txt. Which CMake version do you use?

**Comment by wil1996** [comment]
Dear author, I completely comply with your requirements: Windows 10 64-bit, CMake 3.9.5, Visual Studio 2017, but this error has always existed, this command is indeed defined.

------------------ 原始邮件 ------------------
发件人: "Jan Bender"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 下午4:29
收件人: "InteractiveComputerGraphics/PositionBasedDynamics"<PositionBasedDynamics@noreply.github.com>;
抄送: "晴天"<75104172@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [InteractiveComputerGraphics/PositionBasedDynamics] Clothdemocompilation failed (#78)




This is strange, the command is defined in Demos/Visualization/CMakeLists.txt which is included in Demos/CMakeLists.txt. Which CMake version do you use?

**Comment by janbender** [comment]
Can you add a message command to Demos/Visualization/CMakeLists.txt to see if the file is included correctly.

**Comment by Jason-Hayes** [comment]
Dear author:
In the compilation process of all demos,i have the same error——"CMake Error at CMakeLists.txt:   (VIS_SOURCE_GROUPS): Unknown CMake command "VIS_SOURCE_GROUPS".My compiling environment is Ubuntu 16.04 LTS, CMakeg 3.12.3, GCC 6.3.0.I don't know how to deal with this problem.

**Comment by janbender** [comment]
The command is defined in Demos/Visualization/CMakeLists.txt. Can you check if this file is correctly loaded by adding a message command to the file?
