### ISSUE TITLE
PositionBasedFluids::solveDensityConstraint uses mass in correction

### ISSUE THREAD

**Issue by AtheMathmo** [InteractiveComputerGraphics/PositionBasedDynamics#81]
Hi!

I _think_ I have spotted a bug: https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/blob/86483ffac0fc30fbdd57196ee4893157e6d72893/PositionBasedDynamics/PositionBasedFluids.cpp#L119 

The density solver uses the mass to scale the kernel gradient in the correction. I do not think that this mass term should be present. E.g. [Section 5.10 in your notes](https://www.animation.rwth-aachen.de/media/papers/2017-EG-CourseNotes.pdf) or Eqn (12) in Position Based Fluids.

**Comment by janbender** [comment]
In our implementation we use the correct SPH formulation. However, Macklin used a simplified formulation in his paper and in our course notes where he assumed that all particles have an equal mass. One example where this assumption fails is when the method is combined with the boundary handling of Akinci et al. which we use in our code.

**Comment by AtheMathmo** [comment]
Ah okay, thank you!
