### ISSUE TITLE
Rigid body emitter

### ISSUE THREAD

**Issue by kayarre** [InteractiveComputerGraphics/PositionBasedDynamics#87]
Is there a way to employ a rigid body emitter similar to that for SPlisHSPlasH, except the rigid bodies are geometries instead of spheres.  An example would be emulate pouring a pitcher full of duckies into a box. 

Where would be a god place to put this or add this feature?

**Comment by janbender** [comment]
A simple way would be to generate all bodies at the beginning. But activate the emitted bodies only at their individual emit time. The emitter step should then be performed before or after a time step.
