### ISSUE TITLE
Save state of simulation

### ISSUE THREAD

**Issue by kayarre** [InteractiveComputerGraphics/PositionBasedDynamics#88]
I am running the Pile scene with a different configuration. Is it possible to save the locations of objects once they come to rest?

I would assume I could just add some kind of save feature that exports the centroid of the sdf for each object?

Where would be a good place to add that feature?

**Comment by janbender** [comment]
Do you want to save the SDF or the geometry? For the geometry you could copy the OBJ exporter from our SPlisHSPlasH repo.

**Comment by kayarre** [comment]
I think the obj file at its last location. I will look at the OBJ exporter. Thank you so much.
