### ISSUE TITLE
"error: could not find git for clone of Ext_Discregrid" issue

### ISSUE THREAD

**Issue by luxorm96** [InteractiveComputerGraphics/PositionBasedDynamics#89]
I am sorry for disturbing you with such a basic issue, but could you help me to solve it? I am building the project with CMake 3.9.5 and VS 2017, but still can't get the Discregrid library. What can I do to get it?

**Comment by janbender** [comment]
You need to install git which is used to install Discregrid.

**Comment by luxorm96** [comment]
Thank you! I've installed git and now everything works fine.
