### ISSUE TITLE
FPS about "DirectPositionBasedSolverForStiffRodsDemo" Project.

### ISSUE THREAD

**Issue by CharlesQHappy** [InteractiveComputerGraphics/PositionBasedDynamics#90]
I set the vs to release mode and ran the "DirectPositionBasedSolverForStiffRodsDemo" example. But the FPS is only 40 more or less, which I don't think it should be according to the data in the corresponding paper. And I'm sure it's not the "vertical synchronization" problem. So what could be the reason?

I'm using vs 2019.
Release x64 mode.

**Comment by janbender** [comment]
Sorry for the late answer. I missed this issue. 
Can you tell me how many milliseconds are required per simulation step. This is reported at the end of the simulation in the console window.
