### ISSUE TITLE
An elastic rod under torsion shows the formation of plectonemes.

### ISSUE THREAD

**Issue by Jason-Hayes** [InteractiveComputerGraphics/PositionBasedDynamics#92]
Dear author:
In the paper of Direct Position-based Slover for Stiff Rods,I am very interested in the deformation of the elastic rod under the action of torsion. I would like to ask how to realize the simulation in the picture based on this code.thank you！
![image](https://user-images.githubusercontent.com/65516947/103867057-afbabc80-5101-11eb-92aa-20e4a0da75fc.png)

**Comment by janbender** [comment]
This is a stiff elastic rod and at one end a motor is attached. However, I think so far nobody had the time to integrate the rods collision detection code of the paper in the library.
