### ISSUE TITLE
Mass-spring vs PBD Cloth

### ISSUE THREAD

**Issue by luxorm96** [InteractiveComputerGraphics/PositionBasedDynamics#98]
Hello, 
 First of all, sorry to ask this question in the current repo, but I couldn't find the answer anywhere else. Have you, guys, ever tried to compare Mass-spring Cloth model to the PBD Cloth? I've searched for comparison papers in web, but it seems like nobody ever wrote about it... Is there a reason why researches do not study such comparison? 
 Sorry once more for posting the issue. If you know any better place to find answers, please, let me know and I'll delete current question. Thank you!

**Comment by janbender** [comment]
I think in current works most researchers either use FEM or PBD. Mass-spring systems are not so popular in research anymore. However, I think in the XPBD paper they showed that XPBD with distance constraints converges to a mass spring system using an implicit Euler.
